In [335]:
import sys
import numpy as np
import numpy.random as rand
print(sys.executable) #проверка на то что блокнот запущен с ядром привязанным к моему созданному виртуальному окружению

C:\Users\MateBook\test\MLtask\homeworks\.venv\Scripts\python.exe


In [155]:
#создание векторов по разлчным признакам
weight_people = np.array([102, 98, 78, 60, 74]) 
wages_people = np.array([50000, 120000, 80000, 95000, 230000])
pupil_classroom = np.array([30, 20, 15, 26, 31, 24])
average_estimation = np.array([3.4, 5.0, 4.3, 3.1])
zeros_array = np.zeros(3, dtype = np.int16) #задание типа элемента массива, в данном случае выделяем два байта под каждый элемент массива. (массив хранит 
ones_array = np.ones(10, dtype = np.int8)
step_five_array = np.arange(0, 40, 5, dtype = np.int16)


weight_people, wages_people, pupil_classroom, avarage_estimation, avarage_estimation.dtype, avarage_estimation.shape, zeros_array, ones_array, ones_array.shape, step_five_array 

(array([102,  98,  78,  60,  74]),
 array([ 50000, 120000,  80000,  95000, 230000]),
 array([30, 20, 15, 26, 31, 24]),
 array([3.4, 5. , 4.3, 3.1]),
 dtype('float64'),
 (4,),
 array([0, 0, 0], dtype=int16),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8),
 (10,),
 array([ 0,  5, 10, 15, 20, 25, 30, 35], dtype=int16))

In [139]:
#создание матриц по различным признакам
weigth_wages_people = np.array([[70, 90, 85, 110], [105000, 130000, 70000, 250000]])
empty_array = np.empty((3,3))
single_matrix = np.eye(5, 5)
class_exellent_student = np.array([['A', 'B', 'C'], [str(3), str(10), str(0)]]) #явное преобразование элементов массива в строки
car_cost = np.array([["BWM", "LADA", "Volvo"], [f"Стоимость: {5500000}", f"Стоимость: {750000}", f"Стоимость: {2400000}"]]) # форматированное встраивание значений переменных прямо в строку
weigth_wages_people, empty_array, single_matrix, empty_array.shape, car_cost, class_exellent_student, class_exellent_student.nbytes, class_exellent_student.dtype, class_exellent_student.shape

(array([[    70,     90,     85,    110],
        [105000, 130000,  70000, 250000]]),
 array([[2.31297541e-311, 2.29175545e-311, 2.30448743e-311],
        [2.31297541e-311, 1.23075756e-312, 1.06099790e-312],
        [1.01855798e-312, 1.01855798e-312, 1.01855798e-312]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 (3, 3),
 array([['BWM', 'LADA', 'Volvo'],
        ['Стоимость: 5500000', 'Стоимость: 750000', 'Стоимость: 2400000']],
       dtype='<U18'),
 array([['A', 'B', 'C'],
        ['3', '10', '0']], dtype='<U2'),
 48,
 dtype('<U2'),
 (2, 3))

In [160]:
#создание тензоров (трехмерных массивов)
people_name_age_gender = np.array([[["Masha", "Sveta", "Ola", "Nastya"], [str(24), str(14), str(45), str(21)], ['F', 'F', 'F', 'F']], [["Kirill", "Maxim", "Dima", "Gosha"], [str(24), str(14), str(45), str(21)], ['M', 'M', 'M', 'M']]])
ones_matrix = np.ones((2,4,4))
zeros_matrix = np.zeros((2, 4, 4))
ones_matrix,zeros_matrix, people_name_age_gender, people_name_age_gender.shape

(array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 array([[['Masha', 'Sveta', 'Ola', 'Nastya'],
         ['24', '14', '45', '21'],
         ['F', 'F', 'F', 'F']],
 
        [['Kirill', 'Maxim', 'Dima', 'Gosha'],
         ['24', '14', '45', '21'],
         ['M', 'M', 'M', 'M']]], dtype='<U6'),
 (2, 3, 4))

In [201]:
#Индексы, срезы, итерации
price_bread = np.array([37.40, 30.99, 21.50, 50.99, 71.24, 76.42, 45.73, 35.45, 38.99])
marks_class_A = np.array([4,4,3,2,5,6,7,9,3,10,7,7,8,2,5,10,9])
marks_class_B = np.array([2,5,6,10,8,2,5,5,6,8,1,10,8,4,7,10,2])
sum_marks = marks_class_A + marks_class_B #сложение поэлементно первого и второго массива (они должны быть размера подходящего размера)
subtr_marks = marks_class_A - marks_class_B #разность поэлементно первого и второго массива (они должны быть размера подходящего размера)
mult_marks = marks_class_A * marks_class_B #умножение поэлементно первого и второго массива (они должны быть размера подходящего размера)
dev_marks = marks_class_A / marks_class_B #деление поэлементно первого и второго массива (они должны быть размера подходящего размера)


marks_class_A[5:8] = 10 #присваевание оценки 10 элементам среза (5, 6, 7 - индексы)
marks_class_A[2] = 8 #присваевание элементу под индексом 2 оценки 8
marks_class_A[2], marks_class_A_transpose, sum_marks, subtr_marks, mult_marks, dev_marks, marks_class_C, marks_class_B, marks_class_A, price_bread[4:6], marks_class_A.shape, marks_class_B.shape #срез элементов начиная с элемента под индексом 4 и заканчивая элементом под индеком 5



(np.int64(8),
 array([ 4,  4,  8,  2,  5, 10, 10, 10,  3, 10,  7,  7,  8,  2,  5, 10,  9]),
 array([ 6,  9,  9, 12, 13,  8, 12, 14,  9, 18,  8, 17, 16,  6, 12, 20, 11]),
 array([ 2, -1, -3, -8, -3,  4,  2,  4, -3,  2,  6, -3,  0, -2, -2,  0,  7]),
 array([  8,  20,  18,  20,  40,  12,  35,  45,  18,  80,   7,  70,  64,
          8,  35, 100,  18]),
 array([2.        , 0.8       , 0.5       , 0.2       , 0.625     ,
        3.        , 1.4       , 1.8       , 0.5       , 1.25      ,
        7.        , 0.7       , 1.        , 0.5       , 0.71428571,
        1.        , 4.5       ]),
 array([ 6,  9,  9, 12, 13,  8, 12, 14,  9, 18,  8, 17, 16,  6, 12, 20, 11]),
 array([ 2,  5,  6, 10,  8,  2,  5,  5,  6,  8,  1, 10,  8,  4,  7, 10,  2]),
 array([ 4,  4,  8,  2,  5, 10, 10, 10,  3, 10,  7,  7,  8,  2,  5, 10,  9]),
 array([71.24, 76.42]),
 (17,),
 (17,))

In [254]:
weight_female_male = np.array([[50,60,45, 65], [90,105,74, 85]])
price_charging = np.array([[[500.1,3500,210],[800.5,902,1530],[3700, 462, 250]],[[1203,370,921], [432,754,215],[975,234,418]]])
get_cos = np.cos(weight_female_male) #получение косинуса
get_max_row = np.max(price_charging, axis = 1) #получение максимальных значений из каждой строки  
get_max_col = np.max(price_charging, axis = 2) #получение максимальных значений из каждого столбца  
transpose_weight_female_male = np.transpose(weight) #транспонировние матрицы
transpose_weight_female_male, get_cos,price_charging, get_max_col, get_max_row

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[ 0.96496603, -0.95241298,  0.52532199, -0.56245385],
        [-0.44807362, -0.24095905,  0.17171734, -0.98437664]]),
 array([[[ 500.1, 3500. ,  210. ],
         [ 800.5,  902. , 1530. ],
         [3700. ,  462. ,  250. ]],
 
        [[1203. ,  370. ,  921. ],
         [ 432. ,  754. ,  215. ],
         [ 975. ,  234. ,  418. ]]]),
 array([[3500., 1530., 3700.],
        [1203.,  754.,  975.]]),
 array([[3700., 3500., 1530.],
        [1203.,  754.,  921.]]),
 array([[50, 60, 45, 65]]))

In [297]:
#индексация 
age_people = np.array([[24,37,25],[10,51,21],[13,15,19],[31,15,26],[13,31,12],[23,76,21]])
age_people, age_people[[2,3],2], age_people[2:3][0], age_people[[4,5]], age_people[4,1], age_people[1:2, : : 2], #получить 0 и 2 элемент из второй строки

(array([[24, 37, 25],
        [10, 51, 21],
        [13, 15, 19],
        [31, 15, 26],
        [13, 31, 12],
        [23, 76, 21]]),
 array([19, 26]),
 array([13, 15, 19]),
 array([[13, 31, 12],
        [23, 76, 21]]),
 np.int64(31),
 array([[10, 21]]))

In [325]:
#итерирование массивов
tenzor = np.array([[[45,52,21],[13,51,53]],[[14,75,23],[12,52,74]]])
tenzor2 = np.array([[[51,235,212],[513,346,326]],[[754,234,752],[123,235,141]]])
for row in tenzor:
    print(row) #row это первая матрица tenzor[0]
    print(' ')
for el in tenzor.flat: #flat - итератор, для перебора по элементам !!!не создает копию массива, если изменим массив, то и итератор поменяется
    #если нужна копия используется flatten
    print(el)
raveled = tenzor2.ravel() #сам массив не меняется
unificationH = np.hstack((tenzor, tenzor2)) #объединение тензоров по стркоам
unificationV = np.vstack((tenzor, tenzor2))
tenzor.shape = (6,2) #меняю размер массива !!!сам массив меняется. если нужно чтобы массив не менялся используется reshape

unificationH, unificationV, raveled.shape,  #атрибут массива

[[45 52 21]
 [13 51 53]]
 
[[14 75 23]
 [12 52 74]]
 
45
52
21
13
51
53
14
75
23
12
52
74


(array([[[ 45,  52,  21],
         [ 13,  51,  53],
         [ 51, 235, 212],
         [513, 346, 326]],
 
        [[ 14,  75,  23],
         [ 12,  52,  74],
         [754, 234, 752],
         [123, 235, 141]]]),
 array([[[ 45,  52,  21],
         [ 13,  51,  53]],
 
        [[ 14,  75,  23],
         [ 12,  52,  74]],
 
        [[ 51, 235, 212],
         [513, 346, 326]],
 
        [[754, 234, 752],
         [123, 235, 141]]]),
 (12,))

In [334]:
#представления и копии массива
original = np.array([45,14,15]) 
view = original.view() #оюъекты хранят одинаковые адреса ДАННЫХ РАЗНЫХ объектов !!!НО в памяти это разные объекты. !!!могут иметь разные метаданные(shape, dtype и тд)
view.shape = (1,3)
car = np.array(["Lada", "Dodge", "Kia"])
equal_car = car #переменные хранят одинаковые адреса ОБЪЕКТОВ здесь именно один и тот же объект 
copy_car = car #здесь уже независимая копия массива car два разных объекта
copy_car is car, original, view, original.shape, view.shape, original.shape, view is original #is - если переменные ссылаются на одну область памяти будет True


(True, array([45, 14, 15]), array([[45, 14, 15]]), (3,), (1, 3), (3,), False)

In [392]:
#Случайные числа 
random_value = rand.random() #псевдослучайны числа на интервале [0, 1)
bottom_range = 10
top_range = 50
extend_range_random = bottom_range + (top_range - bottom_range) * random_value #расширение диапозона от bottom_range до top_range
random_int = rand.randint(10, 20, 5) #массив из 5 слуайных чисел в диапозоне от 10 до 20 !!!20 не включительно
distribution = rand.uniform(0,10,10) #Равномерное распределение - когда все значения в диапазоне равновероятны: [0, 10]
mean_value = np.mean(distribution) #вычисление среднего арифметического
pseudo_rand = rand.seed(100000)
pseudo_rand = rand.randint(10, 20, 2)
extend_range_random, randon_int,distribution, pseudo_rand, mean_value

(47.80803535056217,
 array([14, 14, 10, 11, 15], dtype=int32),
 array([9.11726572, 6.41163507, 4.02220024, 0.8719419 , 7.0591666 ,
        4.35521182, 2.21279194, 8.09535167, 6.45390979, 4.48455179]),
 array([19, 17], dtype=int32),
 np.float64(5.3084026542798926))